### ISSUE TITLE
Pytanie odnośnie Położenia 'bazy danych' smsów i jej połączenia z UE-kiem

### ISSUE THREAD

**Issue by CZOLGOWUS** [pgum/Nokia-PK-2022#15]
Zastanawiam się, w jaki sposób powinniśmy doprowadzić do połączenia bazy danych SMS-ów z UE-kiem. 
Mamy w tym momencie pliki z implementacją bazy w folderze UE/Application/SMSDB. Aczkolwiek mam wrażenie ze lepszym miejscem mogłoby być QtApplicationEnvironment i kiedy bym to zaimplementował to następnie zmieniłbym konstruktor w UserPort by przyjmował jeszcze właśnie bazę danych z tego appEnv jak całą resztę. Tylko nie wiem, czy jest to dobra droga i czy nie zostawić tego po prostu w Application i nie dodawać niczego do ApplicationEnvironment tylko od razu do np. UserPort.

**Comment by PiotrNycz** [comment]
SMSy nie są częścią UserPort'u ani innego portu. Są po prosty odrębnym obiektem.
Nie jest też powiedziane w specyfikacji że muszą przetrwać wyłączenie/właczenie telefonu -- więc może to być zaimplementowane jako zwykły kontener z STLa.
Jak konieczna jest persystencja -- to może to być zwykły plik zapisywany na bieżąco a czytany przy starcie -- jeżeli istnieje.

W zadnym wypadku nie można zmieniać nic w katalogu QtApplicationEnvironment!!! Jest to wyraźnie powiedziane w specyfikacji.
